@echo off
echo Downloading Node.js v20.18.0 LTS...
curl -L -o "%TEMP%\nodejs.msi" "https://nodejs.org/dist/v20.18.0/node-v20.18.0-x64.msi"
echo Installing Node.js...
msiexec /i "%TEMP%\nodejs.msi" /quiet /norestart
echo Waiting for installation...
timeout /t 15
echo Done! Check with: node --version
